adding "extern crate ferris_says" and a small note
Without "extern crate ferris_says" cargo fails to build the program due to error[E0432]: unresolved import `ferris_says`. Also, adding a small note about handling of dashes in Rust identifiers.